#!/usr/bin/env python3
'''
Helper script to request access to a certain host.
'''

import click
import json
import keyring
import os
import requests
import yaml


KEYRING_KEY = 'ssh-request'

CONFIG_DIR_PATH = click.get_app_dir('ssh-request')
CONFIG_FILE_PATH = os.path.join(CONFIG_DIR_PATH, 'ssh-request.yaml')


@click.command()
@click.argument('host', metavar='user@host')
@click.option('-u', '--user', help='Username to use for authentication', envvar='USER')
@click.option('-p', '--password', help='Password to use for authentication')
@click.option('-r', '--reason', help='Reason for this access request', prompt='Please enter a reason')
@click.option('--url', help='SSH Access Granting Service URL', envvar='SSH_ACCESS_GRANTING_SERVICE_URL')
def main(host, user, password, reason, url):
    # sdf
    parts = host.split('@')
    if len(parts) > 1:
        username = parts[0]
    else:
        username = user

    hostname = parts[-1]

    if not url:
        if not os.path.exists(CONFIG_FILE_PATH):
            os.makedirs(CONFIG_DIR_PATH, exist_ok=True)
            url = click.prompt('Please enter the SSH Access Granting Service URL')
            config = {'url': url}
            with open(CONFIG_FILE_PATH, 'w') as fd:
                yaml.dump(config, fd)

        with open(CONFIG_FILE_PATH, 'rb') as fd:
            config = yaml.safe_load(fd)
        url = config['url']

    password = password or keyring.get_password(KEYRING_KEY, user)

    if not password:
        password = click.prompt('Password', hide_input=True)

    if not url.endswith('/access-requests'):
        url = url.rstrip('/') + '/access-requests'
    data = {'username': username, 'hostname': hostname, 'reason': reason}
    click.secho('Requesting access to host {hostname} for {username}..'.format(**vars()), bold=True)
    r = requests.post(url, headers={'Content-Type': 'application/json'}, data=json.dumps(data), auth=(user, password))
    if r.status_code == 200:
        click.secho(r.text, fg='green', bold=True)
    else:
        click.secho('Server returned status {code}: {text}'.format(code=r.status_code, text=r.text), fg='red', bold=True)

    keyring.set_password(KEYRING_KEY, user, password)


if __name__ == '__main__':
    main()
