FROM ubuntu:latest

ADD entrypoint.sh /entrypoint.sh

RUN apt-get update && \
    apt-get install -y openssh-server && \
    mkdir /root/.ssh && \
    chmod 700 /root/.ssh && \
    mkdir /var/run/sshd
EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]
